language: node_js
services:
- postgresql
before_script:
- npm run sequelize db:create
- npm run sequelize db:migrate
env:
- POSTGRES_USER=postgres NODE_ENV=test POSTGRES_HOST=localhost
node_js:
- '8'
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: YcmzBJsB7R/ve4uK7kZZnA60OL0LZ4L5M56p9P5610/nNrC8yp1s7KDZNcsd93EhFWcDFoQSFrQCXxuGHuq4IcRLX3J5swUZA0+fH9PViUWDCjierPOUVAb7wFLBFSEHS3g51faL9lZC0NQngtqyCEIqRc5vRbLMKQDCrkSeoHfRwz3xteHZ192NQkLMCmhJQGXAxyj+6+2a1IazDH+FjKS0BiS9c68jKme5t5Fz4frk9a56Rz7xa4gHt/zOajXa1AqcOwqJpBcw5hGNO/8SAMz10HT7IdPKvmhekBb3sF9FYTYTmBxv2sbeMOuqvCFbZOp+38enh1RQPQV0XLsma3+9jITEnevjldrvw2hiUFyz8jTaQxX382a8A+0oGCODqbXCk6r7/fmMIS025DUqUzhuafRxpTimCsPGm5PMkplVtl7eDBWh5O8LDmeH1So47eVFaE2lRFtWtuu/ouvsnjUkAoAuMxqULDYnTL6g6cLEPSp4hRJ1V0RECE0OI0pLo1BLprDzSUdgZNZHQHkj5/2YjTJgjhyDYRhPbsNTncqzGq0MvtP/iObkYrL899X6M8Fm89jXpSQYQPsWopX8Sz3RWS9SiQu6BB8e6q7+MfRWCCEEe+cUJpvFoac8EfPL3gA91jwf3rmaPZnEEQmAPXj/V+EJrvhtrhUPKnwhBVE=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-sequelizejs
