language: node_js
services:
- postgresql
before_script:
- npm run sequelize db:create
- npm run sequelize db:migrate
env:
- POSTGRES_USER=postgres NODE_ENV=test POSTGRES_HOST=localhost
node_js:
- '8'
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: TVnNcjl1Ju8OB8yPpNg/Q2DriYLNLTugF3CKI2otcb+xTpjJ8si+HImjDtq4M/YPL4k1es+6GM6OU6PeMBOZPIekwERPOnBtRrnaJg47/flKexwfQUREeXVZySL94Qj+XT/fZlK8BvzIABTj6NLyml0uJQtTG7bprNRQt4veZ7oubB7RApCd7Ndqw8pE1j/86hAUHx7VufhIWhiWTbJCJGuICEsBSLm/fTzPzyXcNJgRcE1UCpoYQdVYwH02rk6G5gYo6fL+rJKl45W0YUoebNOrkHsW+VJ9TGuvnGpHff8Zr4ZboyWzKQoTwHVgjTTKRW6EBphpIHVBeikb1r85Ci6sN1bVrYcj+xRJ+4LruS2kXuAfGmnaVERRsnlafJoyIqA9Cua9yqhkOxK7hZqwl2Vrmbe8JZxah9yuqCP8tPij9ta4GtjxQKErKILSB+OGIOWLyRrV7KJa9ENwkY9b2poYDgBRwXvQw4D30WFAqZnraSoQdaiAG/Q2ROu0/7n1RTzO8xVu81y7bHXVlKdNC2brOIYqz0Zog1v0is0gKYW37U+kKhkGRb9T7DXNECxD32zgCDNF5QqRzkZL+6Uu6cX8WLmlpF1QCCe1bLQ6NpmcE1QuUvWahN4xmuc1SgASQ+SkYzcKdqenHBOQGfTHF3bOgFxA+lYWTWXBKYwNaIc=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-sequelizejs
