language: node_js
services:
- postgresql
before_script:
- npm run sequelize db:create
- npm run sequelize db:migrate
env:
- POSTGRES_USER=postgres NODE_ENV=test POSTGRES_HOST=localhost
node_js:
- '8'
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: wojciech.g.krysiak@gmail.com
  api_key:
    secure: p01lFNLvDZBLGOPpiE0bT5e+r8R0u/lOOFr+eE8Mu2ojpDLA7UnBpmaTAH8YmsOgNPYAzGrlP72jtRwFMSG+hgggh6i44OgQ43jqSEuGRsvcNqRDYp41Wd7HbGKULInKJXGnr6gGkmzSanWyAEyoiwC9/w7bPNLi/N2skjINUkXRzMoyVaceEcol3124QlDGproao31TJi7eFFE4V1kBt0Sm6VemP4/biWri0tf81nQ+4HfBkFCZvbceBZLNHCg7QlvFY6oZyqI96faw8hkR7zDiG0sk25AGt7bsS7z+Hlw3DInE8XiDw7bFnWRANw4L7aORF/mV0Km3MedXW5kiQofqeUhpc6JbkjnTnM+HnyWqzfTBs9Q8SI4UpTh/F4pJEMUAd1v40pf+tSv1SQhUPgTSK7u3R4y/QstjsPeaajbmDge3j38ZgXqaA4Swrp3SHJvzG9d3PFFLKjkjZ1EnhtV/bBrgpsWQuW7snW5fXj7YTM4Tvt6SB7xw1oQrhNRp7Kj6QiUmoNXhz1E2/3K485iWiOIjuhr+5b3AwsQ2DoZs7QPQNtfe9/I5rM6WX2gug/GphsebaIB5NEWBUmK9i/WRwiIzedbbCvBiPeNM8Al0SoQUkJFXIxL8zDwjWKwyJqb3M71sykew5xknSPxDkSnTL0LxvwkdC12WXjxRIeA=
  on:
    tags: true
    repo: SoftwareBrothers/admin-bro-sequelizejs
