language: node_js
services:
  - postgresql
before_script:
  - npm run sequelize db:create
  - npm run sequelize db:migrate
env:
  - POSTGRES_USER=postgres NODE_ENV=test POSTGRES_HOST=localhost
node_js:
  - '8'
script:
  - npm run lint
  - npm test